# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1mctpANTqbdWPe5mR1YjRsNIus3w5nNCI
"""

print ("Hello Devangini")

import numpy as np

A = np.array([[30,31,40], [41,50,51], [60,61,70]])

print(np.linalg.det(A))

import numpy as np

A = np.array([[20,10],[50,10]])

print("\nTrace of A:", np.trace(A))

import numpy as np

A = np.array([[-3,2,-5],[2,-3,4],[1,1,1]])

B = np.array([[3,2],[1,4],[5,3]])

C = np.dot(A,B)

C.shape

import numpy as np

a = np.array([[2,3],[5,-4]])

b = np.array([20,27])

res = np.linalg.solve(a,b)

print(res)

import numpy as np
A = np.array([[55,5],[35,15]])

eig_val,eig_vec = np.linalg.eig(A)

print('Eigen values\n',eig_val)

print('Eigen vector\n',eig_vec)

import numpy as np

A = np.array([[1,2],[3,4]])

print(np.linalg.det(A))

min(max(False,-3,-4), 2,7)

x = 5
y = "John"
print (type(x))
print (type(y))

test_list = [1,6,3,5,3,4]
i = 3
if i in test_list:
        print("Element Exists")
else:
        print("Element Doesn't Exists")

from datetime import date
year = int(input('Enter current year: '))
month = int(input('Enter current month: '))
day = int(input('Enter current day: '))

d = date(year, month, day)
print("Today's date is : ",d)

print (9%2)

i = 1
while i <= 10:
    print(i)
    i += 1

a = int(input("Enter a number: "))

b = 0

for i in range(a + 1):

   b += i

print("The sum of all numbers from 1 to the given number is: ", b)

for FizzBuzz in range(51):
    if FizzBuzz % 3 == 0 and FizzBuzz % 5 == 0:
        print("FizzBuzz")
        continue
    elif FizzBuzz % 3 == 0:
        print("Fizz")
        continue
    elif FizzBuzz % 5 == 0:
        print("Buzz")
        continue
    print(FizzBuzz)

a="9"
b=" "
i= int (input("Enter number of rows:"))
j=0

for k in range (i,-1,-1):
  print ((j*a)+(k*b))
  j=j+1

n=4
for i in range(n):
  for j in range(i+1):
    print ('*',end='')
  print()
for i in range(n):
  for j in range(i,n-1):
    print ('*',end='')
  print()

import numpy
def main():

    numbers1 = 1
    listWithEvenNumbers = []

    while numbers1 < 6:
        print(f"Enter even number{numbers1}")
        num = int(input("Enter number: "))
        if num % 2 == 0 or num == 0:
            listWithEvenNumbers.append(num)
            numbers1 = numbers1 + 1
        else:
            print("Number is not even, try again")

    numbers2 = 1
    listWithOddNumbers = []

    while numbers2 < 6:
        print(f"Enter Odd number{numbers2}")
        num = int(input("Enter number: "))
        if num % 2 != 0:
            listWithOddNumbers.append(num)
            numbers2 = numbers2 + 1
        else:
            print("Number is not odd, try again")


    n = sum(listWithEvenNumbers)
    print("Sum of even numbers: ", n)
    m = numpy.prod(listWithOddNumbers)
    print("Prodct of odd numbers: ", m)
    o = abs(n-m)
    print("Absolute difference of sum and product: ", o)

    if o % 2 == 0:
      print (f"{o} is not a prime number")
    else:
      print (f"{o} is a prime number")

main()

i = int (input("Please enter a number:"))

if i % 2 == 0:
      print (f"{i} is not a prime number")
else:
      print (f"{i} is a prime number")
print()

class Item:

  def __init__(self,name,price,quantity):
    self.name = name
    self.price = price
    self.quantity = quantity

  def Name():

class Item:


    def __init__(self, name, price, quantity):
        self.name = name
        self.price = price
        self.quantity = quantity


    def set_name(self, name):
        self.name = name


    def set_price(self, price):
        self.price = price


    def set_quantity(self, quantity):
        self.quantity = quantity



    def get_name(self):
        return self.name

    def get_price(self):
        return self.price

    def get_quantity(self):
        return self.quantity

    def get_value(self):
        return self.price*self.quantity

def main():

    inventory = make_list()


    print('Here is the data you entered:')
    show_list(inventory)

def make_list():

    item_list = []


    print('Enter data for three items.')
    for count in range(1, 4):

        print('Item number ' + str(count) + ':')
        name = input('Enter name of item: ')
        price = float(input('Enter price of item: '))
        quantity = float(input('Enter quantity: '))
        print()


        items = Item(name, price, quantity)

        item_list.append(items)

        return item_list


def show_list(item_list):
    for item in item_list:
            print('Item name is: ',item.get_name())
            print('Item price is: ',item.get_price())
            print('Item quntity is: ',item.get_quantity())
            print('Total value is: ',item.get_value())
            print()


main()

import re
string1='startaddress:0xA0,func1address:0xC0'
string2='endaddress:0xFF,func2address:0xB0'
print(bool(re.search(r'0xB0',string1)))
print(bool(re.search(r'0xB0',string2)))